

application:
  name: "webapp-demo"
  port: 8080
  


image:
  repository: registry-1.docker.io/yogita20/webapp
  tag: 0.2
  pullPolicy: Always
   
replicaCount: 1
revisionHistoryLimit: 0

probes:
       liveness:
         path: /health
         initialDelay: 5
       readiness:
         path: /health
         initialDelay: 30

resources:
    limits:
        cpu: "0.5"
        memory: 256M
    requests:
        cpu: "0.5"
        memory: 256M
   
 

