apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-demo
  labels:
    app: webapp-demo

spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-demo
      
      
  template:
    metadata:
      labels:
        app: webapp-demo
        
    spec:
      containers:
        - name: webapp-demo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/bin/sh"]
          args: ["-c","sh /usr/local/tomcat/bin/startup.sh;while true; do echo hello; sleep 10;done"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
          ports:
            - name: http
              containerPort: {{ .Values.application.port }}
              protocol: TCP
          # livenessProbe:
          #    httpGet:
          #      path: {{ .Values.probes.liveness.path }}
          #      port: {{ .Values.application.port }}
          #    initialDelaySeconds: {{ .Values.probes.liveness.initialDelay }}
          # readinessProbe:
          #    httpGet:
          #      path: {{ .Values.probes.readiness.path }}
          #      port: {{ .Values.application.port }}
          #    initialDelaySeconds: {{ .Values.probes.readiness.initialDelay }}
          env:
            - name: App_Name
              value: {{ .Values.env.app }}
