apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-demo
  labels:
    app: webapp-demo
    

spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-demo
     
      
  template:
    metadata:
      labels:
        app: webapp-demo
        
    spec:
      containers:
        - name: webapp-demo
          image: "yogita20/webapp:0.3"
          command: ["/bin/sh"]
          args: ["-c","sh /usr/local/tomcat/bin/startup.sh;while true; do echo hello; done"]
          imagePullPolicy: Always
          resources:
            limits:
              memory: 256M
              cpu: 0.5
            requests:
              memory: 256M
              cpu: 0.5
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
