apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
  labels:
    app: {{ .Values.application.name }}
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31884
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.application.name }}
