apiVersion: v1
kind: Service
metadata:
  name: webapp-demo
  labels:
    app: webapp-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    Protocol: TCP
  selector:
    app: webapp-demo
